import Cslib.Languages.LambdaCalculus.LocallyNameless.Untyped.Basic
import Cslib.Languages.LambdaCalculus.LocallyNameless.Untyped.LcAt
import Cslib.Languages.LambdaCalculus.LocallyNameless.Untyped.ListFullBeta
import Cslib.Languages.LambdaCalculus.LocallyNameless.Untyped.FullBetaConfluence
import Cslib.Languages.LambdaCalculus.LocallyNameless.Untyped.FullBetaEtaConfluence
import Cslib.Languages.LambdaCalculus.LocallyNameless.Untyped.LeftmostReduction
import Cslib.Foundations.Data.HasFresh
import FokkerChallenge.Basic
import FokkerChallenge.FamousCombinator
import FokkerChallenge.EnhancedCslib.Basic
import FokkerChallenge.EnhancedCslib.FlipApp
import FokkerChallenge.EnhancedCslib.LeftMost
import FokkerChallenge.EnhancedCslib.BetaNormalForm
import FokkerChallenge.EnhancedCslib.Closedunderapp
import FokkerChallenge.EnhancedCslib.List
import FokkerChallenge.EnhancedCslib.HeadNFSpineEta
import FokkerChallenge.EnhancedCslib.ReflTransGenWithSteps
import FokkerChallenge.EnhancedCslib.HeadRed
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Finset.Insert
import Mathlib.Data.Finset.Union

namespace Cslib

namespace LambdaCalculus.LocallyNameless.Untyped.Term

/-!
# Naming a locally nameless term with only the two names `x` and `y`

A locally nameless term `t : Term String` comes from a *closed named* term whose
variables are drawn from the two-element set `{"x", "y"}` exactly when

* `t` contains no free variable (an `fvar` could only come from a free variable
  of the named term),
* every de Bruijn index of `t` points at an enclosing `abs`, and
* the enclosing abstractions can be labelled by `x`/`y` in such a way that no
  index is *shadowed*: if `bvar i` refers to the `i`-th enclosing binder, then
  none of the `i` binders strictly inside it may carry the same name.

With only two names the last condition is a system of constraints on *adjacent*
binders: `bvar i` (for `i ≥ 1`) forces the `i` innermost enclosing binders to be
pairwise-equally named and different from the `i`-th one.  Hence satisfiability
can be decided by one traversal collecting constraints of the form
"binders number `m` and `m+1` of the current context have (un)equal names".

This file defines the decision procedure `LambdaLN.namableXY : Term String → Bool`,
proves it correct (`LambdaLN.namableXY_iff`), and checks it on a list of terms.
-/


/-- Named lambda terms, with variable names given by strings. -/
inductive NTerm where
  /-- A variable occurrence. -/
  | var : String → NTerm
  /-- A lambda abstraction binding the given name. -/
  | lam : String → NTerm → NTerm
  /-- An application. -/
  | app : NTerm → NTerm → NTerm
  deriving DecidableEq, Repr

namespace NTerm

/-- `idx v ctx` is the position of the first occurrence of `v` in `ctx`, if any. -/
def idx (v : String) : List String → Option ℕ
  | [] => none
  | w :: ws => if w = v then some 0 else (idx v ws).map (· + 1)

/-- The locally nameless term denoted by a named term, in a context `ctx` listing
the names of the enclosing binders, innermost first.  A variable that does not
occur in `ctx` becomes a free variable. -/
def toLN (ctx : List String) : NTerm → Term String
  | var v => match idx v ctx with
             | some i => Term.bvar i
             | none => Term.fvar v
  | lam v b => Term.abs (toLN (v :: ctx) b)
  | app a b => Term.app (toLN ctx a) (toLN ctx b)

/-- `WN ctx u` says that the named term `u` is well scoped in the context `ctx`
(every variable occurrence is bound by `ctx` or by an enclosing binder of `u`)
and that all its binders use one of the two names `"x"`, `"y"`. -/
def WN : List String → NTerm → Prop
  | ctx, var v => v ∈ ctx
  | ctx, lam v b => (v = "x" ∨ v = "y") ∧ WN (v :: ctx) b
  | ctx, app a b => WN ctx a ∧ WN ctx b

/-- All names occurring in a named term. -/
def names : NTerm → List String
  | var v => [v]
  | lam v b => v :: names b
  | app a b => names a ++ names b

end NTerm

/-! ## The decision procedure -/

/-- The constraints generated by the occurrence `bvar i`: the `i`-th enclosing
binder must differ from the next one inside it, and the `i - 1` binders inside
that one must all be named alike.  A pair `(m, b)` means: binders number `m` and
`m + 1` of the current context are named differently iff `b = true`. -/
def bvarConstr : ℕ → List (ℕ × Bool)
  | 0 => []
  | i + 1 => (i, true) :: (List.range i).map (fun m => (m, false))

/-- Two constraint lists are compatible when they do not require different
things of the same pair of binders. -/
def compatible (L₁ L₂ : List (ℕ × Bool)) : Bool :=
  L₁.all fun p => L₂.all fun q => !(p.1 == q.1) || (p.2 == q.2)

/-- Reindex the constraints when leaving an abstraction: constraints about the
abstraction just left and its parent are discharged, the others shift down. -/
def shiftConstr (L : List (ℕ × Bool)) : List (ℕ × Bool) :=
  L.filterMap fun p => match p.1 with
    | 0 => none
    | m + 1 => some (m, p.2)

/-- Collect the naming constraints of a term sitting under `d` abstractions.
Returns `none` if the term is unnameable (it has a free variable, a dangling
index, or contradictory constraints). -/
def constraints : Term String → ℕ → Option (List (ℕ × Bool))
  | Term.fvar _, _ => none
  | Term.bvar i, d => if i < d then some (bvarConstr i) else none
  | Term.abs t, d => (constraints t (d + 1)).map shiftConstr
  | Term.app a b, d =>
      match constraints a d, constraints b d with
      | some L₁, some L₂ => if compatible L₁ L₂ then some (L₁ ++ L₂) else none
      | _, _ => none

/-- `namableXY t` decides whether the locally nameless term `t` is the image of a
closed named lambda term using only the two variable names `"x"` and `"y"`. -/
def namableXY (t : Term String) : Bool := (constraints t 0).isSome

/-! ## Correctness -/

/-- A context satisfies a constraint list. -/
def Sat (ctx : List String) (L : List (ℕ × Bool)) : Prop :=
  ∀ m b, (m, b) ∈ L → ∀ a c, ctx[m]? = some a → ctx[m + 1]? = some c →
    ((a ≠ c) ↔ b = true)

/-- A constraint list is consistent if it never demands two different things of
the same pair of binders. -/
def Consistent (L : List (ℕ × Bool)) : Prop :=
  ∀ m b b', (m, b) ∈ L → (m, b') ∈ L → b = b'

/-- The other of the two names. -/
def flipXY (v : String) : String := if v = "x" then "y" else "x"

/-! ### Basic lemmas about `idx` -/

theorem idx_eq_some_get {v : String} : ∀ {ctx : List String} {i : ℕ},
    NTerm.idx v ctx = some i → ctx[i]? = some v ∧ ∀ j < i, ctx[j]? ≠ some v := by
  intro ctx
  induction ctx with
  | nil => intro i h; simp [NTerm.idx] at h
  | cons w ws ih =>
      intro i h
      simp only [NTerm.idx] at h
      by_cases hw : w = v
      · simp [hw] at h
        subst h; subst hw
        exact ⟨by simp, by intro j hj; omega⟩
      · simp [hw] at h
        obtain ⟨k, hk, rfl⟩ := h
        obtain ⟨h1, h2⟩ := ih hk
        refine ⟨by simpa using h1, ?_⟩
        intro j hj
        match j with
        | 0 => simpa using fun hc => hw hc
        | j+1 => simpa using h2 j (by omega)

theorem idx_of_get {v : String} : ∀ {ctx : List String} {i : ℕ},
    ctx[i]? = some v → (∀ j < i, ctx[j]? ≠ some v) → NTerm.idx v ctx = some i := by
  intro ctx
  induction ctx with
  | nil => intro i h _; simp at h
  | cons w ws ih =>
      intro i h1 h2
      match i with
      | 0 =>
          simp at h1
          simp [NTerm.idx, h1]
      | i+1 =>
          have hw : w ≠ v := by
            intro hc; exact h2 0 (by omega) (by simpa using hc)
          simp only [NTerm.idx, if_neg hw]
          rw [ih (by simpa using h1) (fun j hj => by simpa using h2 (j+1) (by omega))]
          simp

theorem idx_isSome_of_mem {v : String} {ctx : List String} (h : v ∈ ctx) :
    (NTerm.idx v ctx).isSome := by
  induction ctx with
  | nil => simp at h
  | cons w ws ih =>
      simp only [NTerm.idx]
      by_cases hw : w = v
      · simp [hw]
      · simp only [if_neg hw]
        rcases List.mem_cons.1 h with h' | h'
        · exact absurd h'.symm hw
        · simpa using ih h'

/-! ### Basic lemmas about the constraint lists -/

theorem mem_bvarConstr {i m : ℕ} {b : Bool} (h : (m, b) ∈ bvarConstr i) :
    (b = true ∧ m + 1 = i) ∨ (b = false ∧ m + 1 < i) := by
  match i with
  | 0 => simp [bvarConstr] at h
  | k+1 =>
      simp [bvarConstr] at h
      rcases h with ⟨rfl, rfl⟩ | ⟨hlt, rfl⟩
      · exact Or.inl ⟨rfl, rfl⟩
      · exact Or.inr ⟨rfl, by omega⟩

theorem mem_shiftConstr {L : List (ℕ × Bool)} {m : ℕ} {b : Bool} :
    (m, b) ∈ shiftConstr L ↔ (m + 1, b) ∈ L := by
  simp only [shiftConstr, List.mem_filterMap]
  constructor
  · rintro ⟨⟨k, c⟩, hmem, heq⟩
    match k with
    | 0 => simp at heq
    | k+1 =>
        simp at heq
        obtain ⟨h1, h2⟩ := heq
        subst h1; subst h2; exact hmem
  · intro h
    exact ⟨(m+1, b), h, by simp⟩

theorem compatible_iff {L₁ L₂ : List (ℕ × Bool)} :
    compatible L₁ L₂ = true ↔ ∀ m b b', (m, b) ∈ L₁ → (m, b') ∈ L₂ → b = b' := by
  simp only [compatible, List.all_eq_true]
  constructor
  · intro h m b b' h1 h2
    have := h _ h1 _ h2
    simpa using this
  · intro h p hp q hq
    have hpq : p.1 = q.1 → p.2 = q.2 := by
      intro hk
      exact h p.1 p.2 q.2 (by simpa using hp) (by rw [hk]; simpa using hq)
    rcases eq_or_ne p.1 q.1 with hk | hk
    · simp [hpq hk]
    · simp [hk]

theorem constraints_key_lt : ∀ (t : Term String) (d : ℕ) (L : List (ℕ × Bool)),
    constraints t d = some L → ∀ m b, (m, b) ∈ L → m + 1 < d := by
  intro t
  induction t with
  | bvar i =>
      intro d L h m b hm
      simp only [constraints] at h
      split at h
      · next hlt =>
          cases h
          rcases mem_bvarConstr hm with ⟨_, h2⟩ | ⟨_, h2⟩ <;> omega
      · exact absurd h (by simp)
  | fvar x => intro d L h; simp [constraints] at h
  | abs t ih =>
      intro d L h m b hm
      simp only [constraints, Option.map_eq_some_iff] at h
      obtain ⟨L', hL', rfl⟩ := h
      have := ih (d+1) L' hL' (m+1) b (mem_shiftConstr.1 hm)
      omega
  | app a b iha ihb =>
      intro d L h m bb hm
      simp only [constraints] at h
      split at h
      · next L₁ L₂ h₁ h₂ =>
          split at h
          · cases h
            rcases List.mem_append.1 hm with hm' | hm'
            · exact iha d L₁ h₁ m bb hm'
            · exact ihb d L₂ h₂ m bb hm'
          · exact absurd h (by simp)
      · exact absurd h (by simp)

theorem constraints_consistent : ∀ (t : Term String) (d : ℕ) (L : List (ℕ × Bool)),
    constraints t d = some L → Consistent L := by
  intro t
  induction t with
  | bvar i =>
      intro d L h m b b' hb hb'
      simp only [constraints] at h
      split at h
      · cases h
        rcases mem_bvarConstr hb with ⟨rfl, h2⟩ | ⟨rfl, h2⟩ <;>
          rcases mem_bvarConstr hb' with ⟨rfl, h4⟩ | ⟨rfl, h4⟩ <;> first | rfl | omega
      · exact absurd h (by simp)
  | fvar x => intro d L h; simp [constraints] at h
  | abs t ih =>
      intro d L h m b b' hb hb'
      simp only [constraints, Option.map_eq_some_iff] at h
      obtain ⟨L', hL', rfl⟩ := h
      exact ih (d+1) L' hL' (m+1) b b' (mem_shiftConstr.1 hb) (mem_shiftConstr.1 hb')
  | app a b iha ihb =>
      intro d L h m b1 b2 hb hb'
      simp only [constraints] at h
      split at h
      · next L₁ L₂ h₁ h₂ =>
          split at h
          · next hcomp =>
            cases h
            have hc := compatible_iff.1 hcomp
            rcases List.mem_append.1 hb with hm | hm <;>
              rcases List.mem_append.1 hb' with hm' | hm'
            · exact iha d L₁ h₁ m b1 b2 hm hm'
            · exact hc m b1 b2 hm hm'
            · exact (hc m b2 b1 hm' hm).symm
            · exact ihb d L₂ h₂ m b1 b2 hm hm'
          · exact absurd h (by simp)
      · exact absurd h (by simp)

/-! ### Satisfaction lemmas -/

theorem two_names_eq {a c v : String} (ha : a = "x" ∨ a = "y") (hc : c = "x" ∨ c = "y")
    (hv : v = "x" ∨ v = "y") (h1 : a ≠ v) (h2 : c ≠ v) : a = c := by
  rcases ha with rfl|rfl <;> rcases hc with rfl|rfl <;> rcases hv with rfl|rfl <;> simp_all

theorem flipXY_ne {v : String} (hv : v = "x" ∨ v = "y") : flipXY v ≠ v := by
  rcases hv with rfl | rfl <;> simp [flipXY]

theorem flipXY_mem (v : String) : flipXY v = "x" ∨ flipXY v = "y" := by
  by_cases h : v = "x" <;> simp [flipXY, h]

theorem bvarConstr_mem_true {i : ℕ} : (i, true) ∈ bvarConstr (i + 1) := by
  simp [bvarConstr]

theorem bvarConstr_mem_false {m i : ℕ} (h : m + 1 < i) : (m, false) ∈ bvarConstr i := by
  match i with
  | 0 => omega
  | k+1 =>
      simp only [bvarConstr, List.mem_cons, List.mem_map, List.mem_range]
      exact Or.inr ⟨m, by omega, rfl⟩

/-- If `v` occurs first at position `i` of `ctx`, the constraints of `bvar i` hold. -/
theorem sat_bvarConstr {ctx : List String} (hctx : ∀ v ∈ ctx, v = "x" ∨ v = "y")
    {v : String} {i : ℕ} (h1 : ctx[i]? = some v) (h2 : ∀ j < i, ctx[j]? ≠ some v) :
    Sat ctx (bvarConstr i) := by
  have hv : v = "x" ∨ v = "y" := hctx v (List.mem_of_getElem? h1)
  intro m b hm a c ha hc
  rcases mem_bvarConstr hm with ⟨rfl, hmi⟩ | ⟨rfl, hmi⟩
  · subst hmi
    rw [h1] at hc
    cases hc
    have hne : a ≠ v := fun hac => h2 m (by omega) (by rw [ha, hac])
    simpa using hne
  · have hane : a ≠ v := fun hac => h2 m (by omega) (by rw [ha, hac])
    have hcne : c ≠ v := fun hac => h2 (m+1) (by omega) (by rw [hc, hac])
    have heq := two_names_eq (hctx a (List.mem_of_getElem? ha))
      (hctx c (List.mem_of_getElem? hc)) hv hane hcne
    simp [heq]

/-- Conversely, a context satisfying the constraints of `bvar i` does not shadow
the `i`-th name. -/
theorem no_shadow_of_sat {ctx : List String} {i : ℕ} (hi : i < ctx.length)
    (hsat : Sat ctx (bvarConstr i)) : ∀ j < i, ctx[j]? ≠ ctx[i]? := by
  match i with
  | 0 => intro j hj; omega
  | k+1 =>
      have hstep : ∀ m, m + 1 < k + 1 → ctx[m]? = ctx[m+1]? := by
        intro m hm
        have h1 := List.getElem?_eq_getElem (l := ctx) (i := m) (by omega)
        have h2 := List.getElem?_eq_getElem (l := ctx) (i := m + 1) (by omega)
        have h3 := hsat m false (bvarConstr_mem_false hm) _ _ h1 h2
        simp at h3
        rw [h1, h2, h3]
      have hdiff : ctx[k]? ≠ ctx[k+1]? := by
        have h1 := List.getElem?_eq_getElem (l := ctx) (i := k) (by omega)
        have h2 := List.getElem?_eq_getElem (l := ctx) (i := k + 1) (by omega)
        have h3 := hsat k true bvarConstr_mem_true _ _ h1 h2
        simp at h3
        rw [h1, h2]
        simpa using h3
      have hconst : ∀ n, n ≤ k → ctx[k - n]? = ctx[k]? := by
        intro n
        induction n with
        | zero => intro _; rfl
        | succ n ih =>
            intro hn
            have hk : k - (n+1) + 1 = k - n := by omega
            rw [← ih (by omega), ← hk]
            exact hstep (k - (n+1)) (by omega)
      intro j hj
      have hjk : ctx[j]? = ctx[k]? := by
        have := hconst (k - j) (by omega)
        rwa [show k - (k - j) = j by omega] at this
      rw [hjk]
      exact hdiff

theorem sat_append {ctx : List String} {L₁ L₂ : List (ℕ × Bool)} :
    Sat ctx (L₁ ++ L₂) ↔ Sat ctx L₁ ∧ Sat ctx L₂ := by
  constructor
  · intro h
    exact ⟨fun m b hm => h m b (List.mem_append_left _ hm),
           fun m b hm => h m b (List.mem_append_right _ hm)⟩
  · rintro ⟨h1, h2⟩ m b hm
    rcases List.mem_append.1 hm with hm' | hm'
    · exact h1 m b hm'
    · exact h2 m b hm'

theorem sat_shift {ctx : List String} {v : String} {L : List (ℕ × Bool)}
    (h : Sat (v :: ctx) L) : Sat ctx (shiftConstr L) := by
  intro m b hm a c ha hc
  exact h (m+1) b (mem_shiftConstr.1 hm) a c (by simpa using ha) (by simpa using hc)

/-- The name to give to an abstraction, given the constraints of its body. -/
def chooseName (ctx : List String) (L : List (ℕ × Bool)) : String :=
  match L.find? (fun p => p.1 == 0) with
  | some p => if p.2 then flipXY (ctx.headD "x") else ctx.headD "x"
  | none => "x"

theorem chooseName_mem {ctx : List String} (hctx : ∀ v ∈ ctx, v = "x" ∨ v = "y")
    (L : List (ℕ × Bool)) : chooseName ctx L = "x" ∨ chooseName ctx L = "y" := by
  have hhd : ctx.headD "x" = "x" ∨ ctx.headD "x" = "y" := by
    match ctx with
    | [] => simp
    | w :: ws => exact hctx w (by simp)
  unfold chooseName
  split
  · split
    · exact flipXY_mem _
    · exact hhd
  · exact Or.inl rfl

theorem find_key_zero {L : List (ℕ × Bool)} {b : Bool} (hb : (0, b) ∈ L)
    (hcons : Consistent L) : L.find? (fun p => p.1 == 0) = some (0, b) := by
  have h1 : (L.find? (fun p => p.1 == 0)).isSome := by
    rw [List.find?_isSome]
    exact ⟨(0, b), hb, by simp⟩
  obtain ⟨p, hp⟩ := Option.isSome_iff_exists.1 h1
  have hmem := List.mem_of_find?_eq_some hp
  have hkey : p.1 = 0 := by
    have := List.find?_some hp
    simpa using this
  have hval : p.2 = b := hcons 0 p.2 b (by rw [← hkey]; simpa using hmem) hb
  rw [hp, ← hval, ← hkey]

theorem headD_of_getElem {ctx : List String} {c : String} (h : ctx[0]? = some c) :
    ctx.headD "x" = c := by
  match ctx with
  | [] => simp at h
  | w :: ws => simp at h; simp [h]

/-- Naming the abstraction with `chooseName` satisfies the constraints of its body. -/
theorem sat_cons {ctx : List String} (hctx : ∀ v ∈ ctx, v = "x" ∨ v = "y")
    {L : List (ℕ × Bool)} (hcons : Consistent L) (h : Sat ctx (shiftConstr L)) :
    Sat (chooseName ctx L :: ctx) L := by
  intro m b hm a c ha hc
  match m with
  | 0 =>
      simp only [List.getElem?_cons_zero, Option.some.injEq] at ha
      simp only [List.getElem?_cons_succ] at hc
      subst ha
      have hfind := find_key_zero hm hcons
      have hhd : ctx.headD "x" = c := headD_of_getElem hc
      have hc2 : c = "x" ∨ c = "y" := hctx c (List.mem_of_getElem? hc)
      unfold chooseName
      rw [hfind, hhd]
      cases b with
      | true => simpa using flipXY_ne hc2
      | false => simp
  | k+1 =>
      simp only [List.getElem?_cons_succ] at ha hc
      exact h k b (mem_shiftConstr.2 hm) a c ha hc

theorem toLN_var_mem {v : String} {ctx : List String} (hv : v ∈ ctx) :
    ∃ i, NTerm.idx v ctx = some i ∧ NTerm.toLN ctx (NTerm.var v) = Term.bvar i := by
  obtain ⟨i, hi⟩ := Option.isSome_iff_exists.1 (idx_isSome_of_mem hv)
  exact ⟨i, hi, by simp [NTerm.toLN, hi]⟩

/-! ### The correctness proof -/

/-- **Correctness of the decision procedure**, in a general context: the terms
denoted by well-scoped named terms over `{"x","y"}` are exactly the ones whose
constraints are collected successfully and satisfied by the context. -/
theorem exists_named_iff (t : Term String) :
    ∀ (ctx : List String), (∀ v ∈ ctx, v = "x" ∨ v = "y") →
      ((∃ u : NTerm, NTerm.WN ctx u ∧ NTerm.toLN ctx u = t) ↔
        ∃ L, constraints t ctx.length = some L ∧ Sat ctx L) := by
  induction t with
  | fvar x =>
      intro ctx _
      constructor
      · rintro ⟨u, hwn, heq⟩
        match u with
        | .var v =>
            obtain ⟨j, _, hjeq⟩ := toLN_var_mem (v := v) hwn
            rw [hjeq] at heq; simp at heq
        | .lam v c => simp [NTerm.toLN] at heq
        | .app u1 u2 => simp [NTerm.toLN] at heq
      · rintro ⟨L, hL, -⟩
        simp [constraints] at hL
  | bvar i =>
      intro ctx hctx
      constructor
      · rintro ⟨u, hwn, heq⟩
        match u with
        | .var v =>
            obtain ⟨j, hj, hjeq⟩ := toLN_var_mem (v := v) hwn
            rw [hjeq] at heq
            cases heq
            obtain ⟨h1, h2⟩ := idx_eq_some_get hj
            have hlt : i < ctx.length := by
              by_contra hcon
              rw [List.getElem?_eq_none (by omega)] at h1
              simp at h1
            exact ⟨bvarConstr i, by simp [constraints, hlt], sat_bvarConstr hctx h1 h2⟩
        | .lam v c => simp [NTerm.toLN] at heq
        | .app u1 u2 => simp [NTerm.toLN] at heq
      · rintro ⟨L, hL, hsat⟩
        simp only [constraints] at hL
        split at hL
        · next hlt =>
            cases hL
            have h1 := List.getElem?_eq_getElem (l := ctx) (i := i) hlt
            have h2 : ∀ j < i, ctx[j]? ≠ some ctx[i] := by
              intro j hj
              have := no_shadow_of_sat hlt hsat j hj
              rwa [h1] at this
            exact ⟨NTerm.var ctx[i], List.mem_of_getElem? h1, by
              simp [NTerm.toLN, idx_of_get h1 h2]⟩
        · exact absurd hL (by simp)
  | abs t ih =>
      intro ctx hctx
      constructor
      · rintro ⟨u, hwn, heq⟩
        match u with
        | .var v =>
            obtain ⟨j, _, hjeq⟩ := toLN_var_mem (v := v) hwn
            rw [hjeq] at heq; simp at heq
        | .app u1 u2 => simp [NTerm.toLN] at heq
        | .lam v c =>
            obtain ⟨hv, hwn'⟩ := hwn
            simp only [NTerm.toLN, Term.abs.injEq] at heq
            have hctx' : ∀ w ∈ v :: ctx, w = "x" ∨ w = "y" := by
              intro w hw
              rcases List.mem_cons.1 hw with rfl | hw
              · exact hv
              · exact hctx w hw
            obtain ⟨L', hL', hsat'⟩ := (ih (v :: ctx) hctx').1 ⟨c, hwn', heq⟩
            refine ⟨shiftConstr L', ?_, sat_shift hsat'⟩
            simp only [constraints, Option.map_eq_some_iff]
            exact ⟨L', by simpa using hL', rfl⟩
      · rintro ⟨L, hL, hsat⟩
        simp only [constraints, Option.map_eq_some_iff] at hL
        obtain ⟨L', hL', rfl⟩ := hL
        have hcons := constraints_consistent t (ctx.length + 1) L' hL'
        have hmem := chooseName_mem hctx L'
        have hctx' : ∀ w ∈ chooseName ctx L' :: ctx, w = "x" ∨ w = "y" := by
          intro w hw
          rcases List.mem_cons.1 hw with rfl | hw
          · exact hmem
          · exact hctx w hw
        obtain ⟨u, hwn, heq⟩ :=
          (ih (chooseName ctx L' :: ctx) hctx').2 ⟨L', by simpa using hL', sat_cons hctx hcons hsat⟩
        exact ⟨NTerm.lam (chooseName ctx L') u, ⟨hmem, hwn⟩, by simp [NTerm.toLN, heq]⟩
  | app a b iha ihb =>
      intro ctx hctx
      constructor
      · rintro ⟨u, hwn, heq⟩
        match u with
        | .var v =>
            obtain ⟨j, _, hjeq⟩ := toLN_var_mem (v := v) hwn
            rw [hjeq] at heq; simp at heq
        | .lam v c => simp [NTerm.toLN] at heq
        | .app u1 u2 =>
            obtain ⟨hw1, hw2⟩ := hwn
            simp only [NTerm.toLN, Term.app.injEq] at heq
            obtain ⟨L₁, h₁, hs₁⟩ := (iha ctx hctx).1 ⟨u1, hw1, heq.1⟩
            obtain ⟨L₂, h₂, hs₂⟩ := (ihb ctx hctx).1 ⟨u2, hw2, heq.2⟩
            have hcomp : compatible L₁ L₂ = true := by
              refine compatible_iff.2 fun m c1 c2 hm1 hm2 => ?_
              have hk : m + 1 < ctx.length := constraints_key_lt a ctx.length L₁ h₁ m c1 hm1
              have e1 := List.getElem?_eq_getElem (l := ctx) (i := m) (by omega)
              have e2 := List.getElem?_eq_getElem (l := ctx) (i := m + 1) (by omega)
              have t1 := hs₁ m c1 hm1 _ _ e1 e2
              have t2 := hs₂ m c2 hm2 _ _ e1 e2
              cases c1 <;> cases c2 <;> simp_all
            refine ⟨L₁ ++ L₂, ?_, sat_append.2 ⟨hs₁, hs₂⟩⟩
            simp only [constraints, h₁, h₂, hcomp, if_true]
      · rintro ⟨L, hL, hsat⟩
        simp only [constraints] at hL
        split at hL
        · next L₁ L₂ h₁ h₂ =>
            split at hL
            · cases hL
              obtain ⟨hs₁, hs₂⟩ := sat_append.1 hsat
              obtain ⟨u1, hw1, e1⟩ := (iha ctx hctx).2 ⟨L₁, h₁, hs₁⟩
              obtain ⟨u2, hw2, e2⟩ := (ihb ctx hctx).2 ⟨L₂, h₂, hs₂⟩
              exact ⟨NTerm.app u1 u2, ⟨hw1, hw2⟩, by simp [NTerm.toLN, e1, e2]⟩
            · exact absurd hL (by simp)
        · exact absurd hL (by simp)

/-- **Main theorem**: `namableXY t` is `true` exactly when `t` is the locally
nameless image of a closed named lambda term all of whose binders are named
`"x"` or `"y"`. -/
theorem namableXY_iff (t : Term String) :
    namableXY t = true ↔ ∃ u : NTerm, NTerm.WN [] u ∧ NTerm.toLN [] u = t := by
  have h := exists_named_iff t [] (by simp)
  simp only [List.length_nil] at h
  rw [namableXY, Option.isSome_iff_exists]
  constructor
  · rintro ⟨L, hL⟩
    exact h.2 ⟨L, hL, by intro m b _ a c ha; simp at ha⟩
  · intro hu
    obtain ⟨L, hL, -⟩ := h.1 hu
    exact ⟨L, hL⟩

/-- A well-scoped term over a context of `x`/`y` names uses only the names
`"x"` and `"y"`. -/
theorem NTerm.onlyXY {u : NTerm} :
    ∀ {ctx : List String}, (∀ v ∈ ctx, v = "x" ∨ v = "y") → NTerm.WN ctx u →
      ∀ v ∈ u.names, v = "x" ∨ v = "y" := by
  induction u with
  | var w =>
      intro ctx hctx hwn v hv
      simp only [NTerm.names, List.mem_singleton] at hv
      subst hv
      exact hctx _ hwn
  | lam w c ih =>
      intro ctx hctx hwn v hv
      obtain ⟨hw, hwn'⟩ := hwn
      have hctx' : ∀ z ∈ w :: ctx, z = "x" ∨ z = "y" := by
        intro z hz
        rcases List.mem_cons.1 hz with rfl | hz
        · exact hw
        · exact hctx z hz
      simp only [NTerm.names, List.mem_cons] at hv
      rcases hv with rfl | hv
      · exact hw
      · exact ih hctx' hwn' v hv
  | app c d ihc ihd =>
      intro ctx hctx hwn v hv
      obtain ⟨h1, h2⟩ := hwn
      simp only [NTerm.names, List.mem_append] at hv
      rcases hv with hv | hv
      · exact ihc hctx h1 v hv
      · exact ihd hctx h2 v hv

/-! ### Producing the named term -/

/-- Build a named term over `{"x","y"}` denoting `t` in the context `ctx`, if
there is one.  The name of an abstraction is chosen from the constraints of its
body, exactly as in the correctness proof. -/
def namedOf (ctx : List String) : Term String → Option NTerm
  | Term.bvar i => (ctx[i]?).map NTerm.var
  | Term.fvar _ => none
  | Term.app a b =>
      match namedOf ctx a, namedOf ctx b with
      | some u, some v => some (NTerm.app u v)
      | _, _ => none
  | Term.abs t =>
      match constraints t (ctx.length + 1) with
      | none => none
      | some L => (namedOf (chooseName ctx L :: ctx) t).map (NTerm.lam (chooseName ctx L))

/-- Build a closed named term over `{"x","y"}` denoting `t`, if there is one. -/
def namedOf? (t : Term String) : Option NTerm := namedOf [] t

/-- Boolean check that a named term only uses the names `"x"` and `"y"`. -/
def NTerm.usesOnlyXY : NTerm → Bool
  | var v => v == "x" || v == "y"
  | lam v b => (v == "x" || v == "y") && usesOnlyXY b
  | app a b => usesOnlyXY a && usesOnlyXY b

def isNamedOfXY (t : Term String) : Bool :=
  (namedOf? t).any NTerm.usesOnlyXY

/-! ### Examples -/

section Examples

/-- `λx. x x` is nameable. -/
example : namableXY (Term.abs (Term.app (Term.bvar 0) (Term.bvar 0))) = true := by rfl

/-- A term with a free variable is not nameable. -/
example : namableXY (Term.fvar "z") = false := by rfl

/-- A dangling index is not nameable. -/
example : namableXY (Term.bvar 0) = false := by rfl

/-- Four nested abstractions are fine as long as no index is shadowed. -/
example : namableXY (Term.abs (Term.abs (Term.abs (Term.abs (Term.bvar 3))))) = true := by rfl

/-- `λa. λb. λc. a b` genuinely needs three names, so it is not nameable with
only `x` and `y`. -/
example :
    namableXY (Term.abs (Term.abs (Term.abs (Term.app (Term.bvar 2) (Term.bvar 1))))) = false := by
  rfl

/-- `namedOf?` produces a witness. -/
example : namedOf? (Term.abs (Term.abs (Term.app (Term.bvar 1) (Term.bvar 0))))
    = some (NTerm.lam "x" (NTerm.lam "y" (NTerm.app (NTerm.var "x") (NTerm.var "y")))) := by rfl

/-- The naming of `λx. x x`. -/
example :
    NTerm.toLN [] (NTerm.lam "x" (NTerm.app (NTerm.var "x") (NTerm.var "x")))
      = Term.abs (Term.app (Term.bvar 0) (Term.bvar 0)) := by
  rfl

end Examples
