import Cslib.Languages.LambdaCalculus.LocallyNameless.Untyped.FullBetaEta
import Cslib.Languages.LambdaCalculus.LocallyNameless.Untyped.LcAt
import FokkerChallenge.EnhancedCslib.Closedunderapp
import FokkerChallenge.EnhancedCslib.List
import Mathlib.Data.Finset.Lattice.Basic

namespace Cslib

namespace LambdaCalculus.LocallyNameless.Untyped.Term

@[simp, scoped grind unfold]
def GenFinset (atoms: List (Term String)) := ClosedUnderApp (fun t => t ∈ atoms)

@[simp, scoped grind unfold]
def Gen (atom : Term String) := GenFinset [atom]

@[simp, scoped grind unfold]
def not_basises (atoms : List (Term String)) : Prop :=
  ∃ y, y.LC ∧ y.fv = ∅ ∧ ∀ t, GenFinset atoms t → t ↠βηᶠ y → False

@[simp, scoped grind unfold]
def not_basis (atom : Term String) : Prop := not_basises [atom]

theorem genfinset_depth {fs M} (h : GenFinset fs M) :
   M.depth <= ((fs.map depth).max?).getD 0 := by
  induction h with
  | base ht =>  rename_i t
                have hle : t.depth ≤ (List.map depth fs).max?.getD 0 :=
                  List.mem_le_max?_getD (List.mem_map_of_mem ht)
                omega
  | app _ _ _ _ => unfold depth; omega

theorem genfinset_subset {l1 l2 M} (hsubset : l1 ⊆ l2) (h : GenFinset l1 M) :
  GenFinset l2 M := by
  induction h <;> grind

/-- A member of the right list of a `Forall₂` is related to some member of the
left list. -/
theorem exists_mem_forall₂_left {α : Type*} {R : α → α → Prop} {l1 l2 : List α}
    (h : List.Forall₂ R l1 l2) {b : α} (hb : b ∈ l2) : ∃ a ∈ l1, R a b := by
  induction h with
  | nil => cases hb
  | cons hab _ ih =>
      rcases List.mem_cons.1 hb with rfl | hb'
      · exact ⟨_, List.mem_cons_self .., hab⟩
      · obtain ⟨a, ha, hR⟩ := ih hb'
        exact ⟨a, List.mem_cons_of_mem _ ha, hR⟩

/-! ## Lifting β-reduction of the atoms -/

/-- **Lifting β-reduction of the atoms, regular version.**  If the atoms of `l1`
β-reduce to the atoms of `l2` componentwise and `N` is a locally closed term
generated by `l2`, then `N` is a β-reduct of a term generated by `l1`.

A regularity assumption is necessary, see `genfinset_forall2_counterexample`. -/
theorem genfinset_forall2_of_lc {l1 l2 : List (Term String)} {N : Term String}
    (hl : List.Forall₂ (Relation.ReflTransGen FullBeta) l1 l2)
    (hN : LC N) (hn : GenFinset l2 N) : ∃ M, GenFinset l1 M ∧ M ↠βᶠ N := by
  revert hN
  induction hn with
  | @base a hmem =>
      intro _
      obtain ⟨b, hb, hstar⟩ := exists_mem_forall₂_left hl hmem
      exact ⟨b, ClosedUnderApp.base hb, hstar⟩
  | @app a b _ _ iha ihb =>
      intro hN
      have hlca : LC a := by cases hN with | app h₁ _ => exact h₁
      have hlcb : LC b := by cases hN with | app _ h₂ => exact h₂
      obtain ⟨M₁, hM₁, hs₁⟩ := iha hlca
      obtain ⟨M₂, hM₂, hs₂⟩ := ihb hlcb
      refine ⟨Term.app M₁ M₂, ClosedUnderApp.app hM₁ hM₂, ?_⟩
      refine (FullBeta.redex_app_l_cong hs₁ ?_).trans (FullBeta.redex_app_r_cong hs₂ hlca )
      apply FullBeta.steps_lc_or_rfl at hs₂
      grind

/-- **Lifting β-reduction of the atoms.**  If every atom of `l1` is locally
closed and the atoms of `l1` β-reduce to the atoms of `l2` componentwise, then
every term `N` generated by `l2` is a β-reduct of a term generated by `l1`. -/
theorem genfinset_forall2 {l1 l2 : List (Term String)}
    (hl : List.Forall₂ (Relation.ReflTransGen FullBeta) l1 l2)
    (hlc : ∀ t ∈ l1, LC t) :
    ∀ N,  GenFinset l2 N -> ∃ M, GenFinset l1 M ∧ M ↠βᶠ N := by
  have hlc2 : ∀ t ∈ l2, LC t := by
    intro t ht
    obtain ⟨a, ha, hstar⟩ := exists_mem_forall₂_left hl ht
    apply FullBeta.steps_lc_or_rfl at hstar
    grind
  intros N hn
  have hN : LC N := by
    induction hn with
    | base hmem => exact hlc2 _ hmem
    | app _ _ iha ihb => exact LC.app iha ihb
  exact genfinset_forall2_of_lc hl hN hn
